name: Publish

on:
  release:
    types: [published]

jobs:
  publish:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write

    steps:
      - uses: actions/checkout@v4
      - uses: nubjs/setup-nub@v0
        with:
          registry-url: "https://registry.npmjs.org"
          token: ${{ secrets.NPM_TOKEN }}
      - name: Install deps
        run: nub install
      - name: Publish package to npm
        run: nub publish --provenance --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
